name: POE Puzzle
description: POE labyrinth puzzle solver
author: tzing
url: https://tzing.github.io/
baseurl: /poe-puzzle

exclude: [
  LICENSE,
  README.md
]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
